version: "3.8"

services:
  db:
    container_name: db
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  db-backup:
    container_name: db_backup
    image: kartoza/pg-backup:15-3.3
    env_file:
      - .env
    volumes:
      - dumps:/backups
    depends_on:
      - db
    restart: on-failure

  parser:
    container_name: parser
    build: .
    env_file:
      - .env
    command: python3 src/main.py
    depends_on:
      - db
      - selenium
    links:
      - selenium
    restart: always

  selenium:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"

volumes:
  db_data:
  dumps: